ticker_universe = {'DUMMY': {'primary_exchange': 'NYSE', 'options': True},

                   'AC': {'primary_exchange': 'TSE', 'options': True},
                   'BMO': {'primary_exchange': 'TSE', 'options': True},
                   'GOOS': {'primary_exchange': 'TSE', 'options': True},
                   'CNR': {'primary_exchange': 'TSE', 'options': True},
                   'ENB': {'primary_exchange': 'TSE', 'options': True},

                   'SPY': {'primary_exchange': 'NYSE', 'options': True},
                   'AMD': {'primary_exchange': 'NASDAQ', 'options': True},
                   'MSFT': {'primary_exchange': 'NASDAQ', 'options': True},
                   'TSLA': {'primary_exchange': 'NASDAQ', 'options': True},
                   'FB': {'primary_exchange': 'NASDAQ', 'options': True},
                   'AFRM': {'primary_exchange': 'NASDAQ', 'options': True},
                   'GM': {'primary_exchange': 'NYSE', 'options': True},
                   'LCID': {'primary_exchange': 'NASDAQ', 'options': True},
                   'UPST': {'primary_exchange': 'NASDAQ', 'options': True},
                   'BA': {'primary_exchange': 'NYSE', 'options': True},
                   'DIS': {'primary_exchange': 'NYSE', 'options': True},
                   'JPM': {'primary_exchange': 'NYSE', 'options': True},
                   'NVDA': {'primary_exchange': 'NASDAQ', 'options': True},
                   'PTON': {'primary_exchange': 'NASDAQ', 'options': True},
                   'TDOC': {'primary_exchange': 'NYSE', 'options': True},
                   'SQ': {'primary_exchange': 'NYSE', 'options': True},
                   'TTWO': {'primary_exchange': 'NASDAQ', 'options': True},
                   'ZM': {'primary_exchange': 'NASDAQ', 'options': True},
                   'BABA': {'primary_exchange': 'NYSE', 'options': True},

                   'BHEL': {'primary_exchange': 'NSE', 'options': True},
                   'HDFCBANK': {'primary_exchange': 'NSE', 'options': True},
                   'TCS': {'primary_exchange': 'NSE', 'options': True},
                   'RELIANCE': {'primary_exchange': 'NSE', 'options': True},
                   'KOTAKBANK': {'primary_exchange': 'NSE', 'options': True},
}
